baseURL: "https://www.kinjo.tech/"
title: Keisei Kinjo (JC)'s Blog
copyright: "Â© 2025 kinjo.tech"
theme: PaperMod
pagination:
  pagerSize: 8

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true
pygmentsUseClasses: true
mainsections:
  - posts

googleAnalytics: G-FRYQ5R2WW9

params:
  env: production
  title: Keisei Kinjo (JC)'s Blog
  description: "DevOps Engineer | Mandarin-Japanese-English trilingual speaker | TokyoðŸ—¼"
  keywords:
    - blog
    - tech
    - developer
    - engineer
    - devops
    - åšå®¢
    - éƒ¨è½æ ¼
    - ãƒ–ãƒ­ã‚°
  author: JC
  # images: [""]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShareButtons:
    - "linkedin"
    - "twitter"
    - "facebook"
    - "reddit"
    - "telegram"
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  social: true

  assets:
    disableHLJS: true
    favicon: favicon.png
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple_touch_icon.png

  label:
    text: "JC"
    icon: /favicon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false
    title: Keisei Kinjo (JC)
    subtitle: "DevOps Engineer | Mandarin-Japanese-English trilingual speaker | TokyoðŸ—¼"
    imageUrl: "/favicon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Kurimmy
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "ðŸ‘‹ Hi there! I'm Keisei Kinjo (JC)"
    Content: >
      > - A Mandarin-Japanese-English trilingual DevOps Engineer base in Tokyo. ðŸ‘¨â€ðŸ’»ðŸ—¼

      > - A basketball and fingerstyle guitar enthusiast. ðŸ€ðŸŽ¸

      > - I hope you find something useful here. If you have any questions or comments, feel free to reach out to me via email. dtjp[@]tutanota.com

  socialIcons:
    - name: email
      url: "mailto:dtjp@tutanota.com"
    - name: github
      url: "https://github.com/aibazhang"
    - name: rss
      url: "/index.xml"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://www.buymeacoffee.com/kinjo"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: archives
      name: Archives
      url: archives/
      weight: 5
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10
    - identifier: Reading
      name: Reading
      url: posts/reading
      weight: 15

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
