baseURL: "https://www.kinjo.tech/"
title: Keisei Kinjo (JC)'s Blog
copyright: "Â© 2025 kinjo.tech"
theme: PaperMod
pagination:
  pagerSize: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true
pygmentsUseClasses: true
mainsections:
  - posts

googleAnalytics: G-FRYQ5R2WW9

params:
  env: production
  title: Keisei Kinjo (JC)'s Blog
  description: Keisei Kinjo (JC)'s Blog
  keywords:
    - Blog
    - Portfolio
  author: JC
  images: ["/favicon.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShareButtons:
    - "linkedin"
    - "twitter"
    - "facebook"
    - "reddit"
    - "telegram"
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  social: true

  assets:
    disableHLJS: true
    favicon: favicon.png
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple_touch_icon.png

  label:
    text: "JC"
    icon: /favicon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false
    title: Keisei Kinjo (JC)
    subtitle: >
      I'm a Mandarin-Japanese-English trilingual DevOps Engineer base in Tokyo. ðŸ—¼
      </br>Kubernetes | Terraform | Golang | Google Cloud | Platform Engineering
      
      </br></br> I love playing [_Fingerstyle guitar_](https://en.wikipedia.org/wiki/Fingerstyle_guitar), reading books, and working out.

      </br> Email me at dtjp[@]tutanota.com
      
      </br></br> Latest Talk (Japanese):
      <iframe class="speakerdeck-iframe" frameborder="0" src="https://speakerdeck.com/player/63ba57500d4745238a203104041cdb95?slide=1" title="SREãŒå®Ÿç¾ã™ã‚‹é–‹ç™ºè€…ä½“é¨“ã®é©æ–°" allowfullscreen="true" style="border: 0px; background: padding-box padding-box rgba(0, 0, 0, 0.1); margin: 0px; padding: 0px; border-radius: 6px; box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 40px; width: 100%; height: auto; aspect-ratio: 560 / 315;" data-ratio="1.7777777777777777"></iframe>

    # imageUrl: "/favicon.png"
    imageWidth: 140
    imageHeight: 140
    imageTitle: Creamyyy

  homeInfoParams:
    Title: "Keisei Kinjo (JC)"
    Content: >
      I'm a Mandarin-Japanese-English trilingual DevOps Engineer base in Tokyo. ðŸ—¼
      </br>Kubernetes | Terraform | Golang | Google Cloud | Platform Engineering
      
      </br></br> I love playing [_Fingerstyle guitar_](https://en.wikipedia.org/wiki/Fingerstyle_guitar), reading books, and working out.

      </br> Email me at dtjp[@]tutanota.com
      
      </br></br> Latest Talk (Japanese):
      <iframe class="speakerdeck-iframe" frameborder="0" src="https://speakerdeck.com/player/63ba57500d4745238a203104041cdb95?slide=1" title="SREãŒå®Ÿç¾ã™ã‚‹é–‹ç™ºè€…ä½“é¨“ã®é©æ–°" allowfullscreen="true" style="border: 0px; background: padding-box padding-box rgba(0, 0, 0, 0.1); margin: 0px; padding: 0px; border-radius: 6px; box-shadow: rgba(0, 0, 0, 0.2) 0px 5px 40px; width: 100%; height: auto; aspect-ratio: 560 / 315;" data-ratio="1.7777777777777777"></iframe>

  socialIcons:
    - name: email
      url: "mailto:dtjp@tutanota.com"
    - name: github
      url: "https://github.com/aibazhang"
    - name: linkedin
      url: "https://www.linkedin.com/in/kinjok/"
    - name: rss
      url: "/index.xml"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: blog
      name: Blog
      url: archives/
      weight: 5
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10
    - identifier: Reading
      name: Reading
      url: posts/reading
      weight: 15

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
