baseURL: "https://kinjo.tech/"
title: J.C.
copyright: "Â© 2024 kinjo.tech"
paginate: 8
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true
pygmentsUseClasses: true
mainsections: 
  - posts

googleAnalytics: G-FRYQ5R2WW9

params:
  env: production
  title: J.C.
  description: "J.C.'s Blog"
  keywords: 
    - blog
    - tech
    - developer
    - engineer
    - devops
    - åšå®¢
    - éƒ¨è½æ ¼
    - ãƒ–ãƒ­ã‚°
  author: J.C.
  # images: [""]
  DateFormat: "January 2, 2006"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShareButtons:
    - "linkedin"
    - "twitter"
    - "facebook"
    - "reddit"
    - "telegram"
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
    favicon: favicon.png
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
    apple_touch_icon: apple_touch_icon.png

  label:
    text: "J.C."
    icon: /favicon.png
    iconHeight: 35

  homeInfoParams:
    Title: "ðŸ‘‹ Hi there! I'm Keisei Kinjo (J.C.)"
    Content: >
      > - A Mandarin-Japanese-English trilingual DevOps Engineer base in Tokyo. ðŸ‘¨â€ðŸ’»ðŸ—¼
      
      > - A basketball and fingerstyle guitar enthusiast. ðŸ€ðŸŽ¸
      
      > - I hope you find something useful here. If you have any questions or comments, feel free to reach out to me via email. dtjp[@]tutanota.com

  socialIcons:
    - name: email
      url: "mailto:dtjp@tutanota.com"
    - name: github
      url: "https://github.com/aibazhang"
    - name: rss
      url: "/index.xml"
    - name: KoFi
      title: Buy me a Ko-Fi :)
      url: "https://www.buymeacoffee.com/kinjo"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: archives
      name: Archives
      url: archives/
      weight: 5
    - identifier: tags
      name: Tags
      url: tags/
      weight: 10
    - identifier: books
      name: Reading Notes
      url: https://aibazhang.github.io/
      weight: 15

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
